# Generated by Django 4.1.7 on 2023-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0)),
                ('customer_name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking')], max_length=20)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='account_balance_constraint', violation_error_message='El balance no puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('account_number__length__gte', 5)), name='account_number_constraint', violation_error_message='El numero de cuenta debe tener entre 5 a 20 carácteres'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('account_type__in', ('savings', 'checking'))), name='account_status_constraint', violation_error_message='Estatus no valido'),
        ),
    ]
